### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by MouadLahlal** [MouadLahlal/chatSoftware#1]
Se chiudo il programma prima di inserire ip/porta della persona da contattare si verifica il seguente errore : 
`ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto`

Testo completo dell'errore :
````
Exception in thread Thread-2 (inoltra_msg):
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-3 (inoltra_msg):
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\Documents\Python\chatSoftware\server\Server.py", line 76, in inoltra_msg
    msg = self.ricevi(mittente)
  File "C:\Users\Admin\Documents\Python\chatSoftware\server\Server.py", line 84, in ricevi
    msg = user.clientsocket.recv(1024)
ConnectionResetError    : self._target(*self._args, **self._kwargs)[WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto

  File "C:\Users\Admin\Documents\Python\chatSoftware\server\Server.py", line 76, in inoltra_msg
    msg = self.ricevi(mittente)
  File "C:\Users\Admin\Documents\Python\chatSoftware\server\Server.py", line 84, in ricevi
    msg = user.clientsocket.recv(1024)
ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto
````

**Comment by MouadLahlal** [comment]
Errore risolto con il commit : bb2eed2f666e7419a24dc7d334880db9d9ee37c0

**Comment by MouadLahlal** [comment]
Errore risolto con il commit : bb2eed2f666e7419a24dc7d334880db9d9ee37c0
